# Generated by Django 5.1.1 on 2025-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='ip',
            field=models.CharField(default='ipaddress', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
