# Generated by Django 5.1.1 on 2025-06-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybadmin', '0002_poste_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='etat',
            field=models.CharField(default='hors_ligne', max_length=20),
        ),
    ]
